### ISSUE TITLE
User is able to edit the playlist

### ISSUE THREAD

**Issue by Nithi-fssa** [fssa-batch3/hariharan.veerakumar__web_project#10]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiODUxNjEzYmUtZWE4MC00NGJlLTllMWYtMTEzNDAwMzE2MmM0IiwiZGVwbG95X2lkIjoiNjQ0MTFkNTMwMGEyMzIwMDA4ZWE2Nzk3IiwiaWQiOiIzNWE3MTc2Yy03MTAwLTQwMGQtOTM0OC02OGY2NTUzZWE5ZTMifQ==)

### Description of issue
There is no separate pages for admin and user.  both pages were mixed and seems to be so confusing. It want to show music list to viewers not to edit them.

### Expected result
Show music to viewers .User should not edit them.

### Actual result
Just show music list to the viewers

### Steps to reproduce
1. It want to show music list to viewers.
2. 
3. 

```
Path:      /pages/music.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--crazy-fitness.netlify.app%2Fpages%2Fmusic.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--crazy-fitness.netlify.app/pages/music.html)

**Comment by Smarthariharan** [comment]
Admin features added in crud features also
