### ISSUE TITLE
User is able to delete gym products 

### ISSUE THREAD

**Issue by Nithi-fssa** [fssa-batch3/hariharan.veerakumar__web_project#11]
### Description of issue
There is no separate pages for both admin and user. User is able to edit and delete all those products and music list.    

### Expected result
User should only see the music list and buy products 

### Actual result
There should be a page for both admin and user or else some logic for both is expected.

### Steps to reproduce
1. User should only see the music list and buy products.
2.  Admin have to edit and delete those products

```
Path:      /pages/outfit.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--crazy-fitness.netlify.app%2Fpages%2Foutfit.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--crazy-fitness.netlify.app/pages/outfit.html)

**Comment by Smarthariharan** [comment]
Features added for admin also
