### ISSUE TITLE
Without giving proper data in User edit page Its showing saving successfully

### ISSUE THREAD

**Issue by Nithi-fssa** [fssa-batch3/hariharan.veerakumar__web_project#12]
### Description of issue
There is no required added for all those input in user profile. It has been redirecting to home page.

### Expected result
Check every input pattern and required fields in user profile page.

### Actual result
Required field should be add in user profile page.

### Steps to reproduce
1. Required field should be add in user profile page.
2.  It should redirect to user set of pages.

```
Path:      /pages/profile.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--crazy-fitness.netlify.app%2Fpages%2Fprofile.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--crazy-fitness.netlify.app/pages/profile.html)

**Comment by Smarthariharan** [comment]
bug fixed by required attribute for every field

**Comment by Smarthariharan** [comment]
bug fixed by required attribute for every field
