### ISSUE TITLE
Only user story is added in readme

### ISSUE THREAD

**Issue by Nithi-fssa** [fssa-batch3/hariharan.veerakumar__web_project#13]
### Description of issue
What is the use of adding admin here. User is able edit , delete and create card. 

### Expected result
Segregate admin and user. Think logic for both and let them sign in.

### Actual result
Admin and user difference should be very clear.

### Steps to reproduce
1.  Admin and user difference should be very clear.
2. Segregate admin and user. Think logic for both and let them sign in.
3. 

```
Path:      /pages/admin_login.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--crazy-fitness.netlify.app%2Fpages%2Fadmin_login.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--crazy-fitness.netlify.app/pages/admin_login.html)

**Comment by Smarthariharan** [comment]
Admin story added in readme
