### ISSUE TITLE
Phone number pattern in registration page

### ISSUE THREAD

**Issue by Nithi-fssa** [fssa-batch3/hariharan.veerakumar__web_project#9]
### Description of issue
In registration page phone number pattern has not given 
Less than ten number is been allowing and redirecting to login page

### Expected result
Redirecting to login page

### Actual result
Phone number pattern has to be given.

### Steps to reproduce
1.  pattern has to be given for phone number
2.  phone number must be in 10 characters
3. 

```
Path:      /pages/sign_in.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-3--crazy-fitness.netlify.app%2Fpages%2Fsign_in.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #3](https://deploy-preview-3--crazy-fitness.netlify.app/pages/sign_in.html)

**Comment by Smarthariharan** [comment]
Validation added in javascript for phone number
